name: Security Vulnerability
description: File a security vulnerability report.
title: "[vuln] <title>"
labels: ["vuln"]

assignees:
  - x55xaa
body:
  - type: markdown
    attributes:
      value: |
        **Please do not report security vulnerabilities through public GitHub issues.**

        Instead, please report them by sending an email to [stefano.cuizza+security@protonmail.com](mailto:stefano.cuizza+security@protonmail.com).
